allowBuilds:
  '@parcel/watcher': true
  '@swc/core': true
  core-js: false
  core-js-pure: false
  es5-ext: false
  esbuild: true
  gatsby: false
  gatsby-cli: false
  lmdb: true
  msgpackr-extract: false
  sharp: true
