name: Test Project Builds
on:
  pull_request:
    branches:
      - main
      - master
    types: [ opened, reopened, synchronize ]
permissions:
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Install pnpm and Node.js
        uses: pnpm/setup@v1
        with:
          runtime: node@22
          cache: true
      - name: Install project dependencies
        run: pnpm install --frozen-lockfile
      - name: Check types
        run: pnpm run typecheck
      - name: Build with Gatsby
        env:
          PREFIX_PATHS: "true"
        run: pnpm run build:gatsby
      - name: Build with Storybook
        run: pnpm run build:storybook
